# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# trigger:
# - master

# # pool:
# #   vmImage: ubuntu-latest

# #Varias plataformas
# strategy:
#   matrix:
#     linux:
#       imageName: "ubuntu-16.04"
#     mac:
#       imageName: "macos-10.14"
#     windows:
#       imageName: "vs2017-win2016"
#   maxParallel: 3

# pool:
#   vmImage: $(imageName)
  
# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# #Tarea para implementación de una aplicación en un sitio web
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
#     includeRootFolder: false

# - script: |
#     npm install
#     npm run build
#   displayName: 'npm install and build'

##V2
#container:# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  uiSource: './'
  uiBuild: '$(uiSource)/build'

pool:
  name: 'Gretalia'
# pool:
#   vmImage: 'ubuntu-latest'


steps:
# - task: CmdLine@2
#   inputs:
#     script: |
#       echo Replace Index.html
#       pushd $(uiSource)/public
#       mv index.release.html index.html
#       popd
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd $(uiSource)
    npm install
    npm run build
    popd
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(uiBuild)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(uiBuild)'
#     ArtifactName: 'release'
#     publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'release'
    publishLocation: 'Container'
- task: PowerShellOnTargetMachines@3
  inputs:
    Machines: 'DESKTOP-NC2RPCF'
    InlineScript: |
      # Write your powershell commands here.
      
      Write-Output "Hello World"